project_id = "upafnptdutyxkxjbonye"

[functions.help-chat]
verify_jwt = false

[functions.generate-pack-sounds]
verify_jwt = false

[functions.purchase-pack]
verify_jwt = false

[functions.songbpm-search]
verify_jwt = false

[functions.music-search-ai]
verify_jwt = false

[functions.admin-get-users]
verify_jwt = false

[functions.get-shared-setlist]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.subscription-stats]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = false

[functions.auto-translate]
verify_jwt = false

[functions.migrate-subscriptions]
verify_jwt = false
